# Generated by Django 5.1.4 on 2024-12-07 15:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auths', '0003_customuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with this email already exists.'}, max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Indicates whether the email is verified.', verbose_name='Is Verified'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='One-Time Password (OTP)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='OTP Created At'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default.jpg', null=True, upload_to='profile_pictures/', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registration Date'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reset_password_otp',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Password Reset OTP'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reset_password_otp_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Password Reset OTP Created At'),
        ),
    ]
