# Generated by Django 5.1.4 on 2024-12-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='custom_category',
            field=models.CharField(blank=True, help_text="Optional custom category if predefined options don't fit.", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='custom_tags',
            field=models.TextField(blank=True, help_text="Optional custom tags separated by commas if predefined options don't fit.", null=True),
        ),
    ]
