# Generated by Django 5.1.4 on 2024-12-09 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Archive', '0002_file_custom_category_file_custom_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='custom_category',
        ),
        migrations.RemoveField(
            model_name='file',
            name='custom_tags',
        ),
    ]
