# Generated by Django 5.1.4 on 2024-12-28 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Problem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='submitter',
            field=models.ForeignKey(blank=True, help_text='If the user is logged in, link to their CustomUser account.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_problems', to=settings.AUTH_USER_MODEL, verbose_name='Submitter'),
        ),
    ]
