# Generated by Django 5.1.4 on 2024-12-28 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Problem', '0002_problem_submitter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='media_files',
        ),
        migrations.AlterField(
            model_name='problem',
            name='submitter_photo',
            field=models.ImageField(blank=True, help_text='Photo of the submitter if provided.', null=True, upload_to='submitter_photos/', verbose_name='Submitter Photo'),
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Image or video file associated with the problem.', upload_to='problem_media/', verbose_name='Media File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the media file was uploaded.', verbose_name='Uploaded At')),
                ('problem', models.ForeignKey(help_text='The problem this media file is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='Problem.problem', verbose_name='Problem')),
            ],
        ),
    ]
