# Generated by Django 5.1.4 on 2025-01-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Problem', '0003_remove_problem_media_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='sdg',
            field=models.CharField(choices=[('1. No Poverty', 'No Poverty'), ('2. Zero Hunger', 'Zero Hunger'), ('3. Good Health and Well-being', 'Good Health and Well-being'), ('4. Quality Education', 'Quality Education'), ('5. Gender Equality', 'Gender Equality'), ('6. Clean Water and Sanitation', 'Clean Water and Sanitation'), ('7. Affordable and Clean Energy', 'Affordable and Clean Energy'), ('8. Decent Work and Economic Growth', 'Decent Work and Economic Growth'), ('9. Industry, Innovation, and Infrastructure', 'Industry, Innovation, and Infrastructure'), ('10. Reduced Inequalities', 'Reduced Inequalities'), ('11. Sustainable Cities and Communities', 'Sustainable Cities and Communities'), ('12. Responsible Consumption and Production', 'Responsible Consumption and Production'), ('13. Climate Action', 'Climate Action'), ('14. Life Below Water', 'Life Below Water'), ('15. Life on Land', 'Life on Land'), ('16. Peace, Justice, and Strong Institutions', 'Peace, Justice, and Strong Institutions'), ('17. Partnerships for the Goals', 'Partnerships for the Goals')], default='1. No Poverty', help_text='The SDG related to the problem.', max_length=50, verbose_name='Sustainable Development Goal (SDG)'),
        ),
    ]
