# Generated by Django 5.1.4 on 2024-12-12 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a compelling title for your idea.', max_length=255, verbose_name='Idea Title')),
                ('problem', models.TextField(help_text='Describe the problem your idea aims to solve.', verbose_name='Problem Addressed')),
                ('solution', models.TextField(help_text='Provide a detailed solution for the problem.', verbose_name='Proposed Solution')),
                ('resources', models.TextField(help_text='List the resources needed to implement your idea.', verbose_name='Estimated Resources Required')),
                ('alignment', models.TextField(help_text="Explain how this idea aligns with the organization's mission.", verbose_name='Alignment with Goals')),
                ('tags', models.CharField(help_text='Enter tags related to your idea, separated by commas.', max_length=255, verbose_name='Tags')),
                ('attachments', models.FileField(blank=True, help_text='Optional. Upload relevant files or images.', null=True, upload_to='idea_attachments/', verbose_name='Attachments')),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Submitted', help_text='Current status of the idea.', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the idea was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the idea was last updated.', verbose_name='Updated At')),
                ('proposer', models.ForeignKey(help_text='The user who proposed this idea.', on_delete=django.db.models.deletion.CASCADE, related_name='proposed_ideas', to=settings.AUTH_USER_MODEL, verbose_name='Proposer')),
            ],
            options={
                'verbose_name': 'Idea',
                'verbose_name_plural': 'Ideas',
                'ordering': ['-created_at'],
            },
        ),
    ]
